### ISSUE TITLE
@synthesize of 'weak' property is only allowed in ARC or GC mode

### ISSUE THREAD

**Issue by coneybeare** [TheAmazingAudioEngine/TheAmazingAudioEngine#101]
New error in cocoapod 1.4.2

![screen shot 2014-07-07 at 1 54 30 pm](https://cloud.githubusercontent.com/assets/35369/3499408/e9a74b6a-05ff-11e4-8202-cedfb4bbb6f8.png)

My project does indeed use arc and has had no additional changes other than updating the TheAmazingAudioEngine cocoapod from 1.3 to 1.4.2

**Comment by knikaha** [comment]
change target to 6.0
