### ISSUE TITLE
Convert pcm to mp3

### ISSUE THREAD

**Issue by Tiger9527** [TheAmazingAudioEngine/TheAmazingAudioEngine#103]
I have to use cpm format to record audio. After filter the noise, the record file should convert to mp3 file. How can I record,filter and transcode in the same time.

**Comment by ninalucklove** [comment]
You may prefer to this step by step guide on how to convert PCM to MP3, WAV, ALAC, FLAC, AC3, AAC, M4A etc: http://www.faasoft.com/articles/pcm-converter-mac-and-windows.html

Hope it can help you more or less.
