### ISSUE TITLE
App Store Validation Failed : Private selector :connected

### ISSUE THREAD

**Issue by fdoyon** [TheAmazingAudioEngine/TheAmazingAudioEngine#110]
This is due to AEAudioController.m:1987 

Calling Connected on an NSObject without casting to the required protocol triggers iTunes' validation.

I am not familiar with AudioBus so I have just commented-out this line as I don't use it... And I wanted to get my app reviewed before iOS8 comes out :dancer: 

```
-(void)audiobusConnectionsChanged:(NSNotification*)notification {
    if ( _inputEnabled ) {
        [self updateInputDeviceStatus];
    }
    if ( [notification.object connected] ) {
        [self start:NULL];
    }
}

```

**Comment by donpark** [comment]
I was able to work around this with following change:
https://github.com/donpark/TheAmazingAudioEngine/commit/7fee048b3bcc36e1c2de61673a2e2938e49cc983

AFAIK property is exposed as public API via getter named `isConnected`.
