### ISSUE TITLE
AERecorder and M4A

### ISSUE THREAD

**Issue by bogardon** [TheAmazingAudioEngine/TheAmazingAudioEngine#113]
so `AEAudioFileWriter` disables and reenables `AVAudioSessionCategoryOptionMixWithOthers` if you record using `kAudioFileM4AType`. the problem I'm running into is that this causes a `AEAudioController#audioRouteChangeNotification` to be called, which creates significant lag. Is there anything we can do here?

**Comment by etamity** [comment]
+1

**Comment by hakanw** [comment]
+1!

**Comment by hakanw** [comment]
There's also actually a sleep for half a second that makes this very laggy! I've commented it out in my own project to speed up things, and am almost wondering if it's a slip.

https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/6131fcaf06e0e4a258c6ea1f7d8aa7f62e79eeaa/TheAmazingAudioEngine/AEAudioController.m#L873

**Comment by michaeltyson** [comment]
I'm just checking the 0.5s sleep thing with Jesse, who added it - there may be good reason it's there (as a means to sidestep multithreading problems, maybe?), but I'm not certain.

The category change is, at least the last time I looked into this, necessary to enable the hardware encoding, but it could be worth seeing if there's any fat to be shed along the process. Patches very welcome.

**Comment by essej** [comment]
I did the sleep in updateWithAudioDescription (a new method I added in the patch) for the same reason there is a sleep in attemptRecoveryFromSystemError... I was finding that tearing down then starting up again immediately when an external audio interface was attached would sometimes cause the external interface to be ignored and it would use the internal instead. The sleep seemed to be needed in those cases. But it could probably be lowered, and perhaps made optional, since the behavior from iOS here is hit-or-miss.

**Comment by hakanw** [comment]
Just a quick bump here. I've disabled the 0.5 second sleep in our app since a few months and I haven't heard of any issues... so I'm wondering if it's really generally needed.

**Comment by michaeltyson** [comment]
(Sorry about the delay, @hakanw) What d'you think, @essej? I haven't got any code that uses this right now, so I can't really test it without the sleep, or with a lower sleep..

**Comment by jaunt** [comment]
Is it possible the requirement to disable the "mix with other" property for AAC encoding has been removed on recent ios versions?  

Here's my problem:

In my app if the user has no headphones connected the audio comes out the device speaker.  If the user triggers audio recording, the call to setCategory:audioSession.category from beginWritingToFileAtPath actually switches the audio to come out the device receiver (phone speaker) just as recording begins.  I have no idea why!  

So, I've now commented out this disable/re-enable of AVAudioSessionCategoryOptionMixWithOthers from beginwritingfiletopath and finishwriting and so far everything seems to work.  My app only supports ios8 and higher.

I guess I'll have to test on all possible devices to be sure, or is there any other way to know if the AAC is broken some how that I'm not toggling that property?

**Comment by michaeltyson** [comment]
Ah! It's been ages since I've looked at this; I wasn't aware that the category flag change wasn't needed any more! I think I'm in favour of removing it. I don't have any more iOS 7 devices lying around any more, unfortunately, so I have no way of knowing if it'll break those...

**Comment by michaeltyson** [comment]
You know, worth it, I think.
