### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by shenroong** [TheAmazingAudioEngine/TheAmazingAudioEngine#127]
This problem is really strange. I follow the instruction to set up my project with The Amazing Audio Engine. If I run my app in simulator first, then run it on the device. I will get this error 

ld: warning: ignoring file Library/Developer/Xcode/DerivedData/game——test-dhdgcsyuzqogtygovvpkxelizgmw/Build/Products/Debug-iphoneos/libTheAmazingAudioEngine.a, missing required architecture arm64 in file Library/Developer/Xcode/DerivedData/game——test-dhdgcsyuzqogtygovvpkxelizgmw/Build/Products/Debug-iphoneos/libTheAmazingAudioEngine.a (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AEBlockChannel", referenced from:
      objc-class-ref in SoundDetect.o
  "_OBJC_CLASS_$_AEAudioController", referenced from:
      objc-class-ref in SoundDetect.o

If I only run my app on device, it works fine. So basically whenever I switch from the simulator to device, I get this error .

**Comment by felakuti4life** [comment]
I'm getting this error too. Weird!

**Comment by michaeltyson** [comment]
Ugh, that's annoying. I get that with the SoundCloud SDK when I switch architectures with my Loopy project file. It's something to do with Xcode not recognizing that the library needs to be rebuilt for the new architecture...

**Comment by lijon** [comment]
It happens to me with TAAE all the time after switching between 32 and
64 bit devices, or simulator. A "clean all" fixes it, but is a bit
annoying since everything need to be recompiled from scratch, not only
TAAE.

**Comment by michaeltyson** [comment]
This may be addressed in SHA 196d2467955ffea283d90c925b690b13f6e9d15c
