### ISSUE TITLE
16 Analyzer Issues detected

### ISSUE THREAD

**Issue by sedwo** [TheAmazingAudioEngine/TheAmazingAudioEngine#131]
![theamazingaudioengine_analyzerissues](https://cloud.githubusercontent.com/assets/1434449/5843949/533c768a-a17e-11e4-8fd7-c2332e3d89fe.png)

**Comment by michaeltyson** [comment]
The analyzer only flags possible issues - I've looked at those already, and last time I looked they weren't problematic. Feel free to indicate otherwise if you see any specific problems.
