### ISSUE TITLE
Is it possible to change audio route?

### ISSUE THREAD

**Issue by shannonchou** [TheAmazingAudioEngine/TheAmazingAudioEngine#134]
I have tried several approachs, but failed.
It seems that the input port and output port must be on the same device. So the audio route is always like "iPhone Microphone and Speaker" or "NDZ-03-GA and NDZ-03-GA". NDZ-03-GA is a bluetooth speaker with a mic. Is it possible to change the audio route to be "iPhone Microphone and NDZ-03-GA"? If so, the iPhone can become a megaphone, and send the live audio stream to the bluetooth speaker!

**Comment by michaeltyson** [comment]
No, this isn't possible on iOS right now, I'm afraid.
