### ISSUE TITLE
3DAudioUnitMixer as Filter?

### ISSUE THREAD

**Issue by audiocommander** [TheAmazingAudioEngine/TheAmazingAudioEngine#136]
Hi, 

first of all my sincerest apologies for posting here and not to the TAAE forum, but I cannot register as the system seriously doubts my humanity (I can't say if it's the "Core Audio" answer or Re-Captcha; gave up after 10 minutes).

I am using TAAE along with multiple AudioUnitFilePlayers and everything is working fine so far. Now I'd like to add a 3D Mixer and spatialize the audio. I have read several topics, looked through the documentation, but I'm still unsure how to proceed. 

I tried:
- Adding the AudioUnit 3D Mixer as a filter, one mixer per channel (is that right? what about the busses?)
- Adding one Mixer as filter on the global output (but don't see how to access channels/busses).
- Looked at the provided examples and tutorials (found pretty much nothing, except this thread that talks about _exchanging_ the used mixer inside TAAE with the 3D Mixer

No matter what I try, I do hear audio, but it's not panned (obviously I did set the distance and azimuth appropriately and I'm aware of the mono source limitation).

I wonder, is that possible with TAAE? And is the approach adding a mixer as filter correct?

Thanks so much!

**Comment by michaeltyson** [comment]
The humanity test answer is "audio" - mind registering and posting there?
