### ISSUE TITLE
Long dropouts in input audio after plugging in headphones

### ISSUE THREAD

**Issue by lukebradford** [TheAmazingAudioEngine/TheAmazingAudioEngine#137]
![inputdropouttestcase](https://cloud.githubusercontent.com/assets/179166/6401299/640c4ede-bdcd-11e4-8a5a-754c9788e9f3.png)
- Download this [test case project](http://www.filedropper.com/inputdropouttestcase)
- Open InputDropoutTestCase.xcworkspace
- Run the app on a device and allow microphone access
- Run the app again, with the debugger attached, and plug in headphones immediately after "Started recording" appears in the log
- Wait until "Finished recording" appears in the log (ten seconds)
- Use iTunes File Sharing to copy InputDropoutTestCase.aiff to your computer, and open it with your favorite audio editor.

I consistently get a file like [this one](http://www.filedropper.com/inputdropouttestcase_1), that is, it has about four and a half seconds of intermittent digital silence after the headphones are plugged in. No errors are reported. This is not limited to AERecorder - I see the same intermittent silence in any input receiver, such as a meter. Anybody have any idea what's going on?

**Comment by michaeltyson** [comment]
Sorry about the delay - this appears to be yet another hardware or system software bug with the iPad Air 2 (at least, that's the device I'm seeing this on too - are you seeing it with any other hardware?).

As you say, it's happening in other apps, even GarageBand, so...probably nothing we can do about it.
