### ISSUE TITLE
Sporadic crashes on addChannel/removeChannel

### ISSUE THREAD

**Issue by keighl** [TheAmazingAudioEngine/TheAmazingAudioEngine#138]
Hey @michaeltyson. Thanks for this awesome software!

I'm getting crashes occasionally while "replacing" channels on the audio controller. Essentially, the flow is like this:

```objc
// setup includes `createChannelGroup`, adding a couple filters
// to the channel group, loading an initial file player, 
// and starting the engine. 

// change to a new track...
[self.audioController stop];
AEAudioFilePlayer *newPlayer = [self buildPlayerWithURL...];

[self.audioController addChannels:@[player] toChannelGroup:_group];

if (self.currentPlayer)
    [self.audioController removeChannels:@[self.currentPlayer] fromChannelGroup:_group];

self.currentPlayer = nil;
self.currentPlayer = newPlayer;

[self.audioController start:NULL];
```

A EXEC_BAD_ACCESS crash sometimes occurs within `channelAudioProducer` at various points. 

Is this an TAAE issue, or I approaching the channel-replace incorrectly?

Thanks a lot! Let me know if you'd like anymore info.

**Comment by michaeltyson** [comment]
Hey @keighl - you're very welcome! Hmm, that doesn't look like a TAAE issue; at least, I couldn't reproduce it within the sample app following those steps. Can you be more specific about that crash? Where is it happening? What's in the stack trace?

Also, note that there's no need to stop and start the audio engine when adding or removing channels - it's much better (and faster) to keep it running.

**Comment by keighl** [comment]
The crash happens at a couple spots:

* [`AEAudioController.m`](https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/master/TheAmazingAudioEngine/AEAudioController.m#L358)
* [`AEAudioController.m`](https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/master/TheAmazingAudioEngine/AEAudioController.m#L379)

I'll remove that `stop` message, see if that helps, and report back. Thanks, man!

Also, here's a stack trace:

![screen shot 2015-03-11 at 12 33 14 pm](https://cloud.githubusercontent.com/assets/149019/6610409/26828ce6-c835-11e4-8223-eae278e13a91.png)

**Comment by michaeltyson** [comment]
Weird! Are you using ARC? Have you tried running the app with the Zombies instrument to see if there's a double-release happening somewhere?

**Comment by keighl** [comment]
Yep, using ARC. Interestingly, removing the start/stop calls around the channel swap seems to have done the trick.

It makes sense that the engine is more performant without stopping/starting it. Does that potentially explain this type of crash too? Again, the flow was like:

* stop engine
* add new channel
* remove previous channel
* start engine
* (all on main queue)

I'm doing some more testing now and will follow up if I discover anything more, but going to close this out for now.

**Comment by michaeltyson** [comment]
It definitely doesn't explain it - there definitely shouldn't be crashes. I have no theories currently =)
