### ISSUE TITLE
Can I filter an audio file directly without playing it?

### ISSUE THREAD

**Issue by huangy10** [TheAmazingAudioEngine/TheAmazingAudioEngine#139]
As mentioned in the title, I want to apply a filter to a given audio file without playing it.
Is this function supported in the amazing audio engine?

**Comment by michaeltyson** [comment]
Not at this stage, no... @lijon made a [pull request](https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/pull/111) a while ago which adds some offline capabilities, but it's not yet able to handle audio input, which I think is necessary before moving forward.

**Comment by LiweiDong** [comment]
how to use AEAudioFileWriter  writer file with any filters ?

**Comment by michaeltyson** [comment]
@LiweiDong You probably want to use AERecorder. Please direct any further questions to the forum: forum.theamazingaudioengine.com
