### ISSUE TITLE
ipod library

### ISSUE THREAD

**Issue by pengwll** [TheAmazingAudioEngine/TheAmazingAudioEngine#142]
i can read the music in ipod library(url ipod-library://item/item.mp3?id=xxxxx)  in iOS7 or later. 
but in iOS6.0 ,it  retures error the method ExtAudioFileRead in file loader file.

**Comment by lijon** [comment]
The ipod library items are not readable by anything but AVPlayer or MPMediaPlayer prior to iOS7.

**Comment by pengwll** [comment]
ok, thanks
