### ISSUE TITLE
TAAE takes huge amount of RAM when playing bigger files

### ISSUE THREAD

**Issue by hakanw** [TheAmazingAudioEngine/TheAmazingAudioEngine#144]
If you try to play a file that is like an hour long, maybe an interview or so, then some devices (iPhone 4S for example) will not even be able to play it. A new iPhone 6+ device will take a few seconds before it starts playing.

The reason is that TAAE loads the *whole file* into memory before playing (see link). A leaner approach would be to read buffers in chunks so it starts quickly and doesn't use so much memory.

https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/master/TheAmazingAudioEngine/AEAudioFilePlayer.m#L56

**Comment by moduscreate** [comment]
I agree with @hakanw. 

I will also say that i used TAE with a custom audio player, and doing a buffered approach with large files with TAE should be trivial to do.

**Comment by michaeltyson** [comment]
Agreed! A few folks have taken a stab at this, but unfortunately it's not been of acceptable quality yet. I need this for an upcoming project, so I'll probably end up doing it myself shortly.
