### ISSUE TITLE
Frequent crashes on resuming from phone call

### ISSUE THREAD

**Issue by eirikurorri** [TheAmazingAudioEngine/TheAmazingAudioEngine#148]
I get frequent crashes in renderCallback when resuming from a phone call. The crash occurs in renderCallback.

Background info: The sounds are coming from AUAudioFilePlayers. I have to activate the session manually by listening to UIApplicationDidBecomeActiveNotification.

More specifically, I am creating AEAudioUnitFilePlayers and adding them to a channel.

When resuming from a phone call, i tried to play a file and got a rate limit error message ("Update graph result -10861 FFFFD593 ˇˇ’") when trying to add a player to a channel.

I´d appreciate any insight into this crash; I've been looking at it for quite a while with little results.

**Comment by eirikurorri** [comment]
Update: It seems like I'm hitting the rate limit when adding a player to a channel after resuming.

**Comment by eirikurorri** [comment]
Update: The crashes are still happening. 

THIS seems to be referencing an invalid pointer in renderCallback.

    __unsafe_unretained AEAudioController * THIS = (__bridge AEAudioController*)channel->audioController;

I also frequently get this error, but not always : AVAudioSessionErrorCodeCannotStartPlaying

I would *love* some input on this.

**Comment by michaeltyson** [comment]
Apologies for the delay, @eirikurorri! I've been away and only just getting through my inbox now. Can you reproduce these crashes with the TAAE sample app?

**Comment by jureflander** [comment]
Hi, I am experiencing the same issue. Little bit more details: 

As mentioned above, `inside renderCallback`:
`__unsafe_unretained AEAudioController * THIS = (__bridge AEAudioController*)channel->audioController;`

when the crash happens `THIS` and `channel` is referencing an invalid pointer i.e. from my loggings it appears that `channel` is referencing an instance that has been deallocated. 

I created the following scenario, in which I got the crash pretty much every time. *Note: this is just for reproduction purposes.
1.) Stop running engine
2.) Remove a channel
3.) Add a channel
4.) Repeat step 2) and 3) 100 times
5.) Start engine


And, I think I might find the solution to that problem(below). Would just like you to confirm if it makes sense? 

From my observations, `renderCallback` doesn't stops triggering until we call `AUGraphDisconnectNodeInput` and `AUGraphUpdate`. And then there is this code:
```
- (OSStatus)updateGraph {
    // Only update if graph is running
    if ( self.running ) {
        // Retry a few times (as sometimes the graph will be in the wrong state to update)
        OSStatus err;
        for ( int retry=0; retry<6; retry++ ) {
            err = AUGraphUpdate(_audioGraph, NULL);
            if ( err != kAUGraphErr_CannotDoInCurrentContext ) break;
            [NSThread sleepForTimeInterval:0.01];
        }
        
        return err;
    }
    return noErr;
}
```
Which doesn't call `AUGraphUpdate` if the engine is not running. Which would mean that in the above test scenario `renderCallback` with already deallocated `channel` parameter would be triggered.

So to fix this, would it make sense to update graph every time regardless of engine running or not? This seems to solve my crashes. Or would that cause any other issues?

**Comment by michaeltyson** [comment]
Damn me-from-the-past for not explaining why it only updates the graph if it's running...I don't know why that is! I agree that it seems the simplest solution is to remove that `self.running` check. I'm not seeing any problems resulting from that.

**Comment by michaeltyson** [comment]
Okay, fixed. Thanks for picking this up, @jureflander

**Comment by jureflander** [comment]
Awesome, thanks man!
