### ISSUE TITLE
Can't use engine in Extension.

### ISSUE THREAD

**Issue by TheHmmka** [TheAmazingAudioEngine/TheAmazingAudioEngine#149]
Hi! UIStatusBar is not available in Extensions (for example custom keyboards). Please. fix it.

**Comment by michaeltyson** [comment]
I don't understand - TAAE does not use UIStatusBar anywhere. Can you clarify the problem you are having?

**Comment by TheHmmka** [comment]
Oh, sorry. Not UIStatusBar but [[UIApplication sharedApplication] applicationState]. :-)

**Comment by michaeltyson** [comment]
Ah, right. Hmm, I don't really have the spare time right now to try to get TAAE working nicely with extensions, I'm afraid. If you'd like to take a crack, I'd be happy to consider a pull request.

**Comment by TheHmmka** [comment]
The same problem here with time. :-) My crack for current project is far from "good to use" but I'll check if I can make it better.
