### ISSUE TITLE
[QUESTION] AEAudioController initialization from background queue

### ISSUE THREAD

**Issue by rokgregoric** [TheAmazingAudioEngine/TheAmazingAudioEngine#154]
It's allowed to initialize an instance of AEAudioController from a background queue?

My initialization looks like:
```swift
let description = AEAudioController.nonInterleaved16BitStereoAudioDescription()
let audioController = AEAudioController(audioDescription: description, inputEnabled: true, useVoiceProcessing: true, outputEnabled: true)
audioController.preferredBufferDuration = 0.05
audioController.inputChannelSelection = [0]
audioController.addInputFilter(gainFilter)
```

I am getting crashes around 5% of the time. All of them happen at 
`updateInputDeviceStatus` -> `performSynchronousMessageExchangeWithBlock`
`processPendingMessagesOnRealtimeThread` -> `TPCircularBufferConsume` -> `assert(buffer->fillCount >= 0);`
but are triggered from `AEAudioController`initialization, `audioController.inputChannelSelection ` or `audioController.addInputFilter()`

**Comment by michaeltyson** [comment]
No, I’m afraid AEAudioController must be init’d on the main thread. Now I think about it, it might be a good idea to add an NSAssert to make sure that’s the case…

Cheers,
Michael

**Comment by rokgregoric** [comment]
Thanks .. that explains it :(
