### ISSUE TITLE
Debug-iphoneos / Debug-iphonesimulator lib's have the same architectures, can't be in the same fat output file

### ISSUE THREAD

**Issue by Lidbetter** [TheAmazingAudioEngine/TheAmazingAudioEngine#158]
**Context:**
```
Taking device build from: /Users/__username__/Library/Developer/Xcode/DerivedData/__project__-fvyxrlovhobfkgdrtptteuwytgwt/Build/Products/Debug-iphoneos
Taking simulator build from: /Users/__username__/Library/Developer/Xcode/DerivedData/__project__-fvyxrlovhobfkgdrtptteuwytgwt/Build/Products/Debug-iphonesimulator
...I will output a universal build to: /Users/__username__/Library/Developer/Xcode/DerivedData/__project__-fvyxrlovhobfkgdrtptteuwytgwt/Build/Products/Debug-universal
lipo: for current configuration (Debug) creating output file: /Users/__username__/Library/Developer/Xcode/DerivedData/__project__-fvyxrlovhobfkgdrtptteuwytgwt/Build/Products/Debug-universal/libTheAmazingAudioEngine.a
```
**Error:**
`fatal error: lipo: /Users/__username__/Library/Developer/Xcode/DerivedData/__project__-fvyxrlovhobfkgdrtptteuwytgwt/Build/Products/Debug-iphoneos/libTheAmazingAudioEngine.a and /Users/__username__/Library/Developer/Xcode/DerivedData/__project__-fvyxrlovhobfkgdrtptteuwytgwt/Build/Products/Debug-iphonesimulator/libTheAmazingAudioEngine.a have the same architectures (armv7) and can't be in the same fat output file`

This build error seems to have something to do with ending storyboard/xib files, the error then occurs when building for simulator.

currently, deleting the files/cleaning will allow the next build/run to succeed

**Comment by michaeltyson** [comment]
Yeah, I've seen this too; and with other libraries. I have no idea how to fix this - it may be an Xcode bug, or maybe there's some extra checking that needs to be done in a script. If someone has any ideas, I'd happily incorporate them, but I don't really have a path forward on this one.

**Comment by Lidbetter** [comment]
So after some experimentation the following seems to work...

In the 'Clean Build Targets' phase I have added the following:
```
echo "Removing .a file, so that a full rebuild of those files occurs, this seems to prevent the `<<files>> have the same architectures and can't be in the same fat output file` bug, this may be fixed in a future version of xcode(?)"
rm -rf "${BUILD_DIR}/${CONFIGURATION}-iphoneos/lib${TARGET_NAME}.a"
rm -rf "${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/lib${TARGET_NAME}.a"
```

I am unsure if `lib${TARGET_NAME}.a` can be relied upon - if this is actually defined somewhere I missed it.

This does not seem to add any significant time to builds (late 2012 mac mini), but that may not be the case with lesser hardware. This is quicker than a full clean a build though, which I often do because I am too lazy to switch to terminal to delete the files.

DISCLAIMER: I have never looked at build scripts before, so this may be a terrible idea, perhaps someone with ANY kind of knowledge on the further reaching implications of the above snippet could give some feedback

**Comment by jeremywhuff** [comment]
Running into this error as well. @michaeltyson - any idea if Lidbetter's solution is safe?

**Comment by michaeltyson** [comment]
I've totally removed all universal build apparatus from the build - if you update to the latest version the problem should go away.

**Comment by jeremywhuff** [comment]
Cool, thanks.

My project was using an older version of TAAE, and I wasn't able to just switch to the latest. However, I did get it working by removing the subproject from my project and adding TAAE in via cocoapods. Specifying the older TAAE commit in the Podfile didn't seem to cause this issue.

So long story short, the cocoapods configuration seems to fix this, even if you're not using the TAAE with the "universal build apparatus" removed.
