### ISSUE TITLE
Broken volume/mute semantics

### ISSUE THREAD

**Issue by srubin** [TheAmazingAudioEngine/TheAmazingAudioEngine#166]
If you mute an `AEAudioPlayable` and then change its volume, the playable starts playing again while still "muted" internally. This is because in the `AEAudioController` KVO, a volume change sets the volume and ignores the mute property. A playable should never have `channelIsMuted == YES` when it's making noise.

You can see this problem in the iOS sample app.

There are two possible solutions to these broken semantics.

* TV remote control semantics.

| Before state | Action | After state |
| ---------------- | -------- | ------------- |
| Unmuted,`x` volume | set `channelIsMuted = YES` | Muted, `x` volume (sets mixer volume to 0) |
| Muted, `x` volume | set `channelIsMuted = NO` | Unmuted, `x` volume |
| Unmuted, `x` volume | set `volume = y` | Unmuted, `y` volume |
| Muted, `x` volume | set `volume = y` | Unmuted, `y` volume |

* Hardware mute semantics (equivalent to pressing a hardware mute toggle button or ripping out a patch cord to mute a channel).

Before state | Action | After state
---------------- | -------- | -------------
Unmuted,`x` volume | set `channelIsMuted = YES` | Muted, `x` volume (sets mixer volume to 0)
Muted, `x` volume | set `channelIsMuted = NO` | Unmuted, `x` volume
Unmuted, `x` volume | set `volume = y` | Unmuted, `y` volume
Muted, `x` volume | set `volume = y` | Muted, `y` volume (mixer still has volume set to 0)

Both are easy fixes. 

For reference, the current semantics in TAAE are:

Before state | Action | After state
---------------- | -------- | -------------
Unmuted,`x` volume | set `channelIsMuted = YES` | Muted, `x` volume (sets mixer volume to 0)
Muted, `x` volume | set `channelIsMuted = NO` | Unmuted, `x` volume
Unmuted, `x` volume | set `volume = y` | Unmuted, `y` volume
Muted, `x` volume | set `volume = y` | Muted, `y` volume

**Comment by srubin** [comment]
Actually, because the `channelIsMuted` is read-only from the `AEAudioPlayable`, we should stick with the hardware semantics.

**Comment by michaeltyson** [comment]
Nice one, yep, agreed!
