### ISSUE TITLE
Bug with channelIsPlaying on AEAudioFilePlayer

### ISSUE THREAD

**Issue by crontab** [TheAmazingAudioEngine/TheAmazingAudioEngine#171]
If you stop/pause an audio file player using channelIsPlaying a couple of times, the current position starts doing weird things: it jumps closer to the end of file, then loops over to the beginning even though loop is NO.

I traced this down to the problem with kAudioUnitProperty_ScheduledFileRegion. As I understand from the code in schedulePlayRegionFromPosition, the idea is that if the file starts playing from a non-zero position, then the remaining portion is scheduled, and at the same time the entire file is scheduled too, in case it is looping.

The problem is that for this second schedule the completion routine is called too early and _currentRegionOffset gets mixed up: it receives a value that's total file length minus the position your playing started at! The result is, playing unexpectedly jumps to the other end of a file.

Could it be that the system gets confused when you call kAudioUnitProperty_ScheduledFileRegion more than once before you start it (with kAudioUnitProperty_ScheduleStartTimeStamp)? Unless I'm missing something, obviously.

**Comment by crontab** [comment]
This is weird. AEAudioFilePlayerCompletionProc() is called at arbitrary times and it can not be used for detecting the end of playing.

**Comment by jeremywhuff** [comment]
The changes to AEAudioFilePlayer that make it stream from disk are very new, and there are some pretty big issues. Working with @michaeltyson to get that resolved.

In the meantime, I recommend either to go back to a previous commit to use the old AEAudioFilePlayer, which doesn't use audio units, or you can use AEAudioUnitFileStreamer here - https://github.com/jeremywhuff/TheAmazingAudioEngine

It has been pretty heavily tested. Most noticeable issue right now is file length miscalculation when the audio controller's sample rate is different than the file's.

**Comment by michaeltyson** [comment]
Should be sorted now, guys! Thanks to @jeremywhuff and co. for the code.
