### ISSUE TITLE
Is it safe to call setAudioSessionCategory while TAAE is running?

### ISSUE THREAD

**Issue by warpling** [TheAmazingAudioEngine/TheAmazingAudioEngine#183]
As far I can tell it is safe? Even when not called from the main thread.

**Comment by michaeltyson** [comment]
I'd probably be best to use AEAudioController's [audioCategory property](http://theamazingaudioengine.com/doc/interface_a_e_audio_controller.html#a3619f39ea58c8cec127e29959e92b481), so it can track it and do the right things (like augmenting the properties like allowing mixing).

**Comment by warpling** [comment]
Yep—That's the one I'm talking about! Seems to not mind being set after start:
