### ISSUE TITLE
Assertion fails on pressing Record in the Sample project

### ISSUE THREAD

**Issue by artemskikh** [TheAmazingAudioEngine/TheAmazingAudioEngine#184]
How to recreate:
Launch the sample on a simulator (any, really, but I was using iPad 2),
Then press Record at the bottom. 
Assertion fails on line 124:
assert(byteCount <= inBufferList->mBuffers[0].mDataByteSize);
in TPCircularBuffer+AudioBufferList.c
function 
bool TPCircularBufferCopyAudioBufferList(TPCircularBuffer *buffer, const AudioBufferList *inBufferList, const AudioTimeStamp *inTimestamp, UInt32 frames, const AudioStreamBasicDescription *audioDescription)

Output prior to crash may vary, e.g.:
TAAE: Buffer duration 0.0029, 128 frames (requested 0.005s, 221 frames)
or
TAAE: Warning: render took too long (0.004624s, should be less than 0.001451s). Expect glitches.

Is it the problem with my hardware? (MacBook Pro (13-inch, Late 2011), OS X Yosemite 10.10.5).

**Comment by michaeltyson** [comment]
I'm afraid I can't reproduce that on my late 2013 Retina MBP! I have seen quite a few weird audio problems with the simulator in the past though - sample rate weirdness, buffer length weirdness. I'm not very surprised this happens from time to time. Better to test on the device, when it comes to audio.
