### ISSUE TITLE
Can I apply following filters with TAAE?

### ISSUE THREAD

**Issue by ruchiragile** [TheAmazingAudioEngine/TheAmazingAudioEngine#190]
I'm new to TAAE and not sure whether its supporting following filters.

Reverb 
Echo (Delay) 
Pitch Shifting 
Studio (Equalizer) 
Fade In/Out

If yes, please provide examples.

If no, any other possibilities?

P.S. I'm frustrated returned user of Superpowered SDK.

**Comment by amitkumar3968** [comment]
@ruchiragile  please have a look at source code. it might help you.

**Comment by michaeltyson** [comment]
Hi @ruchiragile. You'll find an example of reverb in the sample app. You might also be interested in [DETAAEFilters](https://github.com/dreamengine/DETAAEFilters), which I'm currently rewriting/integrating into TAAE itself - these are simple wrappers around the built-in audio units provided by Apple.

**Comment by ruchiragile** [comment]
@michaeltyson @amitkumar3968 Yes I've checked the samples. In which, I've played with Reverb filter. But I'm looking for other filters (as I mentioned in my question). Is there a way to get it done with TAAE. Please help.

**Comment by ruchiragile** [comment]
@michaeltyson, how many filters are possible with @DETAAEFilters from my list? 

I found following:

Reverb
Delay

Any others?

**Comment by michaeltyson** [comment]
Check the latest commit - you inspired me to finish off and commit the integration =) There are 13

**Comment by ruchiragile** [comment]
@michaeltyson, Yes – Thanks!!

However, still my question, that amazing 13 list includes only 2 filters out my list.

Still looking for, Fade In/Out | Pitch Shifting | Equilizer – That would be awesome if you confirm if this is possible with TAAE. And provide some hint to get start on it. Thanks a ton for your last commit :+1:

**Comment by michaeltyson** [comment]
Pitch is in there (NewTimePitch), as is EQ (ParametricEQ). Fades aren't - you'll need to do that yourself, maybe using vDSP_vrampmul?

**Comment by ruchiragile** [comment]
@michaeltyson, thanks thanks thanks ! For now, I've following filters in my pocket, Pitch | Delay | EQ and Reverb. My last question for you is, how do I get output file (on which filteres applied). I'm not sure, if I'm clear to you. So let me give an example:

Suppose: I'm running your sample code, on which I've applied Reverb filter, now I want to save that audio along with that filter.

How its possible with TAAE? Please provide some hint or sample code.

**Comment by michaeltyson** [comment]
Take a good look at the sample code, @ruchiragile. Truly, it's all there - please take a look at it.

**Comment by ruchiragile** [comment]
@michaeltyson, I can't find my self an example. Where it is?

**Comment by michaeltyson** [comment]
Right here: https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/master/TheEngineSample/iOS/ViewController.m#L632

**Comment by ruchiragile** [comment]
@michaeltyson, but that's for recording only. When I run the sample, I am only able to records the things, what if a file in my bundle on which I want to apply "Reverb" filter, then will save it as a new file?

I'm looking for that thing directly. 

P.S. as I mentioned earlier, I'm frustrated user of SuperpoweredSDK – so I feel that with TAAE everything will be simple and clear. :+1:

**Comment by michaeltyson** [comment]
Ahh, I see, you mean non-realtime processing. That's not really a thing in TAAE at the moment - it's pretty much a real-time audio engine, not an offline processing one. There's a [pull request](#111) for a sorta-offline processing system, but I'm not quite happy with it yet, so it's still pending. You're welcome to try it out, though.

Otherwise, you'll need to drive the process yourself, using an AEAudioFileLoaderOperation with a block and an AEAudioFileWriter. I'm afraid you'll need to drop to Core Audio to feed audio to the filter, via a callback.

**Comment by ruchiragile** [comment]
:disappointed: Not so good, after working for a day I found :floppy_disk: – This is not something that I was expecting from TAAE. If you're providing online processing then what's the problem with offline? (Even you'll save some data bytes as well :laughing:) Anyways, I :bow: to you for support instantly and properly for through out the day. One day, I'll come and check if this is possible or not. You should make it.
