### ISSUE TITLE
Conflict with AVPlayer

### ISSUE THREAD

**Issue by donpark** [TheAmazingAudioEngine/TheAmazingAudioEngine#191]
Before AVPlayer is used, everything is perfect but after video starts playing get a stream of following error messages:

>TAAE: AEAudioController.m:479: AudioConverterConvertComplexBuffer result 1768846202 696E737A insz

I'm using version 1.5 under iOS 8 and 9. Any idea why? I did notice that # audio input frames changes from 1024 to a mix of 940, 941, and 1 frames after AVPlayer starts playing.

**Comment by donpark** [comment]
When I try master branch of TAAE under iOS 9, I no longer get above error but instead gets this:

>TAAE: Mismatch between received input buffer size (940 frames) and reported frame count (941).

**Comment by michaeltyson** [comment]
Looks like AVPlayer's playing silly buggers with the audio session. The latest code (master) should take care of audio buffer mismatches; does it actually work for you? That message is just a warning expressing that there's something weird going on, but it should recover.

**Comment by donpark** [comment]
Ha. Doubt this funny business of asking for 1 frame occasionally is part of Apple's intentional design.
Re whether it works, surprisingly, it does -- in a wobbly way -- but I think that's just due to streaming video on top of separate live audio streaming.
Guess I'll just have to pay my respect to the Jitter God and cross my fingers for future iOS improvements.

**Comment by bogardon** [comment]
jfjfjhfj

**Comment by bogardon** [comment]
asdf
