### ISSUE TITLE
AEAudioUnitChannel With Soundfont No Longer works

### ISSUE THREAD

**Issue by hoddez** [TheAmazingAudioEngine/TheAmazingAudioEngine#195]
I've been using an AEAudioUnitChannel with a soundfont to play midi tracks and notes. This has worked up until 1.4.8 I believe.

I see that there was some refactoring done in the setup of this channel but I have been unable to isolate the exact problem. I will keep trying.

EXPECTED BEHAVIOUR:
Should play midi sounds using soundfont

ACTUAL BEHAVIOUR:
Plays midi sounds using generic tones (without soundfont)

Here is the code I am using to setup the AEAudioUnitChannel:
```objc
AudioComponentDescription component = AEAudioComponentDescriptionMake(kAudioUnitManufacturer_Apple,
                                                                          kAudioUnitType_MusicDevice,
                                                                          kAudioUnitSubType_Sampler);
    
    NSError * __autoreleasing error = NULL;
    AEAudioUnitChannel *channel = [[AEAudioUnitChannel alloc]
                                   initWithComponentDescription:component];
    [channel setupWithAudioController:audioController];

    if ( !channel || error) {
        NSLog(@"Error with Channel Creation");
    }
    
    AUSamplerBankPresetData bpdata;
    bpdata.bankURL  = (__bridge CFURLRef) presetURL;
    bpdata.bankMSB  = kAUSampler_DefaultMelodicBankMSB;
    bpdata.bankLSB  = kAUSampler_DefaultBankLSB;
    bpdata.presetID = presetNumber;
    
    OSStatus result = noErr;
    result = AudioUnitSetProperty(channel.audioUnit,
                                  kAUSamplerProperty_LoadPresetFromBank,
                                  kAudioUnitScope_Global,
                                  0,
                                  &bpdata,
                                  sizeof(bpdata));
    [audioController addChannels@[channel]];
```

**Comment by michaeltyson** [comment]
You need to move your initialisation into a block passed into the init method ("preInitializeBlock" parameter), as the audio unit is now created after adding to the audio controller.

A good practices tip: always wrap your core audio calls in AECheckOSStatus, so you can see when they fail; this would probably have been clear then.

**Comment by hoddez** [comment]
That works. Thanks!
