### ISSUE TITLE
Intermittent (but regular!) Audio Session Interrupted -> Engine Stopped messages

### ISSUE THREAD

**Issue by ephemer** [TheAmazingAudioEngine/TheAmazingAudioEngine#202]
Hi, until this week we have been using TAAE 1.4.6 in production. Apart from some infrequent crash reports everything seemed fine. Trying to track down another bug lead me to update to the latest version (at time of writing 1.5.2).

Now I very often (maybe in about 50% of audio sessions) I get a log in the debugger informing me the "Audio session [was] interrupted" soon after starting, after which I get "TAAE: Stopping Engine". Any ideas why this could be the case? New logic re: interruptions? Could it be because the render function takes too long sometimes? (It sometimes does take too long, but given that we're processing input and _not_ producing audio output, this infrequent case is not important to us).

The only thing I've changed in the program code is that the engine is now inited and started on the main thread instead of a background one (as dictated by the new NSThread isMainThread assert on init).

Thanks for your time

**Comment by michaeltyson** [comment]
Hi! Ahhh, that's exceptionally weird, I've never seen that before. You're not running any other apps that could be interrupting the session? Have you tried older TAAE versions to identify that a specific version started doing this?

**Comment by ephemer** [comment]
Hi @michaeltyson, thanks for your reply. Haven't narrowed it down more exactly to a particular version just yet, but now I know you're on board I will, and I'll get back to you :) Happy Monday

**Comment by ephemer** [comment]
I forgot to mention, there are no other apps running as such, but we are using TAAE from within a hybrid web app, alongside HTML5 video, so in that sense yes, there's a (big black box) potential source of conflicts. Was fine in the past though

**Comment by michaeltyson** [comment]
Ah, that could well be it - it can be messy combining audio stuff sometimes. Not impossible, but it can be tricky. If it worked in the past though, we should be able to isolate what the change was, though.
