### ISSUE TITLE
Microphone Permissions asked too soon

### ISSUE THREAD

**Issue by ephemer** [TheAmazingAudioEngine/TheAmazingAudioEngine#203]
Hi, as an aside to https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/issues/202: the reason we had been initing TAAE in a background thread was to reduce UI lag on init. We can't just init TAAE along with the app because otherwise the user is asked to allow access to their microphone before we have a chance to onboard them as to _why_. Importantly, the user is asked well before the AEAudioController is started. This to me is counter-intuitive and is the basis for creating an issue about it.

In the meantime: what are the best practices regarding time of init, allowing control of when the Mic Permissions are requested? Thank you

**Comment by ryh** [comment]
Only when you need it :microphone: , because users will deny it when the app do not need a Mic Permissions, then you can not easily ask them to change that decision.

**Comment by ephemer** [comment]
@ryh, we are currently initing when we need it. This causes an unacceptable delay in the UI though, especially when inited in the main thread, as is now a requirement.

The question was about how to init, then later ask for mic permissions. Any ideas would be much appreciated

**Comment by michaeltyson** [comment]
One option would be to init without input enabled, and then enable it at a later point, as needed. Sorry about the delay, flat out over here =)

**Comment by mipstian** [comment]
@michaeltyson what is the recommended way to do that?

**Comment by michaeltyson** [comment]
Check the docs for the init options: basically, you just init with the default options, not with input enabled. Then you set inputEnabled to YES when you're ready.

**Comment by mipstian** [comment]
Thanks. Didn't find it right away because `inputEnabled` is `readonly`. For anyone else reading this, just call `- (BOOL)setInputEnabled:(BOOL)inputEnabled error:(NSError**)error` :)

**Comment by ephemer** [comment]
My memory of this is that one half of the process didn't work as I expected it to: either that having inputEnabled to off on init produced the mic permissions dialogue anyway, or that setInputEnabled caused TAAE to reinit itself anyway, which kinda defeated the point in doing it this way. It's been a while since I looked at it, I'll have another look and get back to you either way

**Comment by VincentSit** [comment]
I think that this design is unreasonable, we should request permission when we start recording, rather than the time of initialization.

Because call `setInputEnabled:` will cause the engine to re-initialize, the audio currently playing will stopped, this is not a good user experience.

For example, our product is a IPCam, with two-way intercom function. We can not request recording permission when the user tap listen button, which will most likely to be rejected.
