### ISSUE TITLE
Offline render mode

### ISSUE THREAD

**Issue by michaeltyson** [TheAmazingAudioEngine/TheAmazingAudioEngine#21]
See aso:

http://forum.theamazingaudioengine.com/discussion/comment/374#Comment_374
http://forum.theamazingaudioengine.com/discussion/comment/502#Comment_502

**Comment by lukebradford** [comment]
Has any further progress been made on this?

Thanks,

Luke

**Comment by huangy10** [comment]
Really need this~

Thanks~

**Comment by Apptation** [comment]
Not sure if this enhancement is planned or not? It would be a great feature.

http://stackoverflow.com/questions/15297990/core-audio-offline-rendering-genericoutput/15361251#15361251

**Comment by michaeltyson** [comment]
I'm working on this for TAAE2 - nearly done, just not quite yet.

**Comment by Augustyniak** [comment]
@michaeltyson Is there any update on this? I can help with the implementation if you give me some tips regarding the implementation's idea.

Btw. Really great work with TAAE2. 👏

**Comment by michaeltyson** [comment]
It's done: http://theamazingaudioengine.com/doc2/interface_a_e_audio_file_output.html#details

**Comment by mgill404** [comment]
!!!
