### ISSUE TITLE
Q reg internal code: callback order

### ISSUE THREAD

**Issue by 32Beat** [TheAmazingAudioEngine/TheAmazingAudioEngine#212]
It seems currently, regardless of the order of callbacktypes in the callback table, the code first chains all filter-callbacks, and then supplies the audio to all receiver-callbacks. 

Should it perhaps be rewritten to process according to storage order? 

That is, if the chain looks like this:

source -> filter1 -> filter2 -> receiver1 -> filter 3 -> receiver2

then receiver1 should receive audio after filter1 and 2 are processed.

**Comment by michaeltyson** [comment]
Could be - it does depend on the semantics somewhat: whether you're monitoring the complete output of a channel and its filters, or just monitoring the output up to a certain point in the chain. I've always gone with the former, as I don't personally have any use for the latter. I suppose there'd be a use case for this, although I can't bring any to mind right now.
