### ISSUE TITLE
New internal design

### ISSUE THREAD

**Issue by 32Beat** [TheAmazingAudioEngine/TheAmazingAudioEngine#216]
To better comprehend the design choices of TAAE, I decided the best course of action was to rebuild from scratch to see what I would come up with. I figured I would automatically encounter the issues or hurdles inherent to audio coding. 

In addition, given the AVFoundation toolbox (basically Apple's choice of objectmanagement), it would be useful to see what parallels or discrepancies would turn up. 

I finally came up with this: https://github.com/32Beat/RMSAudio.git

It is so different from TAAE that it seems relatively moot to make any comparisons. 
A couple noteworthy differences: 
- RMSAudio uses an object tree instead of the protocol approach, which does seem to make life significantly easier for the programmer. I'm not saying that it was a bad choice in your case, just noticing the difference. 
- RMSAudio does allow multiple audioOutputs, and Apple hints at the availability of multiroute, so a singular global engine would certainly not be correct.

The MainViewController has some commenting added to hint at the design. I intend to take some time next to add more comprehensible commenting and documentation.

**Comment by michaeltyson** [comment]
Cool stuff, @32Beat, looks good! I've wondered in the past about redoing TAAE with a more decentralised architecture - this looks nice.
