### ISSUE TITLE
lldb crashes for TAAE  1 and TAAE 2

### ISSUE THREAD

**Issue by markjeschke** [TheAmazingAudioEngine/TheAmazingAudioEngine#243]
@michaeltyson, 

For some reason, any Xcode projects with TAAE 1 or TAAE 2 (including the SDK samples), are crashing for me under El Capitan (10.11.16) on a MacBook Air (13-inch 2015). It just crashes upon deploy. I've restarted my computer, but my TAAE projects are still crashing. 

Is this happening for you or anyone else? What's odd, is, the apps seem to publish and operate fine on my iPhone 5S physical device, despite their run and build crashes. Weird...

Thanks for your help and time.

Take care,
Mark

![taae2-sample](https://cloud.githubusercontent.com/assets/1577928/17240309/83c68204-551f-11e6-82a3-b2fe36d9dc42.png)
![taae1-sample](https://cloud.githubusercontent.com/assets/1577928/17240310/83c7b6a6-551f-11e6-92a6-a08fc7691f0e.png)

**Comment by michaeltyson** [comment]
If you take a peek at the symbols in the stack navigator on the left, you'll see it's actually an exception, not a crash; this is how some Core Audio internals work as part of their normal signal flow. It's dumb, and it makes using the catch-all exception breakpoint thing infuriating to use, but it's the Core Audio team's fault, not mine =) Just disable your exception breakpoint and all will work.

**Comment by markjeschke** [comment]
@michaeltyson, 

You're right. I'm sorry that I missed that. Thank you for the swift response and help. I truly appreciate your time and expertise.

Take care,
Mark

**Comment by michaeltyson** [comment]
No worries!
