### ISSUE TITLE
AEAudioFileLoaderOperation crash when output channels > 8

### ISSUE THREAD

**Issue by jeremywhuff** [TheAmazingAudioEngine/TheAmazingAudioEngine#245]
This is due to line 132 of AEAudioFileLoaderOperation:

`SInt32 channelMap[8];`

When `_targetAudioDescription.mChannelsPerFrame > 8`, `main` will crash when it returns.

This apparently affects AEMemoryBufferPlayer and AESequencerChannel.

**Comment by michaeltyson** [comment]
Ouch. Thanks for pointing that out! 😳
