### ISSUE TITLE
channelAudioProducer BAD ACCESS

### ISSUE THREAD

**Issue by jmarshallgtl** [TheAmazingAudioEngine/TheAmazingAudioEngine#247]
Hey Michael, not sure if you are still supporting TAAE1 but i've found a memory issue when removing a channel from the audio controller then adding it straight back again. My app has to do this when moving an AEPlayable object from one channel group to another.

Please see the attached TAAE sample project. I've modified the "oneshotPlayButtonPressed:" function to recreate the memory issue in the "channelAudioProducer" callback (Sometimes the bad access can be elsewhere).

Open in the simulator iPad air 9.3 and just keep quickly pressing the "one shot" button and it should crash eventually, takes a few goes :). It's possibly more likely to happen on the simulator or quicker devices.

Cheers!

[TheAmazingAudioEngine-1.5.7.zip](https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/files/454657/TheAmazingAudioEngine-1.5.7.zip)

**Comment by mobinzk** [comment]
I had the same issue and used the repo from this PR and resolved my issue, hope this helps you too.
https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/pull/213

**Comment by jmarshallgtl** [comment]
Thanks mobinzk, i'll look into it.

**Comment by michaeltyson** [comment]
I think I've fixed this now guys - can you confirm?

**Comment by jeremywhuff** [comment]
With the 0ce20a6 commit, I'm getting a crash at launch with the console output:

```
2016-09-06 20:25:45.105 Prime[6440:1595041] TAAE: Setting audio session category to AVAudioSessionCategoryPlayback
2016-09-06 20:25:45.113 Prime[6440:1595041] TAAE: Audio session initialized (input available, audio route 'iPhone Microphone and Speaker') HW samplerate: 44100
2016-09-06 20:25:45.151 Prime[6440:1595041] TAAE: Engine setup
2016-09-06 20:25:45.152 Prime[6440:1595041] TAAE: Buffer duration 0.046, 2048 frames (requested 0.046s, 2029 frames)
2016-09-06 20:25:45.152 Prime[6440:1595041] TAAE: Starting Engine
```

It's crashing on line 3433 with EXC_BAD_ACCESS.

`        AEChannelRef channel = group ? group->channels[i] : _topChannel;`

I can see that group looks like it is probably a legit object. However i is 2991019, which seems wrong.

I can prevent the crash by setting breakpoints, so it appears to be a multithreading thing. If I get through startup that way, then the app seems as though it's not crashing like it used to. I have a test action that crashes about 10% of the time on 1.5.6, and it didn't crash after 30 trials.

**Comment by michaeltyson** [comment]
Bugger. Kay, I'll take another crack at it. 

FYI, My goal over the next month or two is to finish off TAAE2 and documentation for an official release, then retire TAAE1. So I'm aiming for functional TAAE1 with minimum labor on my part.
