### ISSUE TITLE
High crash rate on TAAE V1.5.6+

### ISSUE THREAD

**Issue by jeremywhuff** [TheAmazingAudioEngine/TheAmazingAudioEngine#248]
I updated my app to use V1.5.6 from (I think) 1.4.7. Upon release, I'm suddenly seeing a very high crash rate. I then ran trials and found that TAAE 1.5.3, 1.5.4, and 1.5.5 won't crash, whereas 1.5.6 and 1.5.7 crash pretty frequently.

I don't have great details at this time, but it appears that pointers internal the AEAudioController are being deallocated and then accessed. One of the most common crashes is AEAudioController line 374:

`    if ( THIS->_automaticLatencyManagement ) {`

because THIS is no longer a valid pointer to the audio controller.

There are also many other lines within AEAudioController that are crashing with similar kinds of issues.

Has anyone else seen similar behavior with the latest releases? What were the major changes to this release?

**Comment by michaeltyson** [comment]
Damn. I think it might be SHA aa469c3e. I've not seen this in Loopy; I guess we're doing something different. Flat out right now and unable to spend much time on this - have you considered checking out TAAE 2 or AudioKit?

**Comment by michaeltyson** [comment]
Ah. Looks like this is a dup of #247, which has repo instructions too. Looking into this now.

**Comment by michaeltyson** [comment]
Should be solved with latest commit, see #247

**Comment by jeremywhuff** [comment]
Moved any further code details to the other thread.

I have been very interested in TAAE 2 and AudioKit, but I haven't had the time to dive into either that far. For this particular project, it's built heavily on TAAE 1, so I don't expect that it's a very easy transition over. Any thoughts on that?

I'm also fairly confused about the licensing of AudioKit - it was originally LGPL, as is CSound which much of it is based on, and that's not compatible with the App Store or with codebases that aren't similarly made public under LGPL (at least to the best of my knowledge). Now AudioKit is MIT, I believe, but I don't see how you can leverage LGPL under an MIT license... I guess I should check out their forums :)

**Comment by michaeltyson** [comment]
It's actually not based on cSound any more, but STK ([MIT](https://ccrma.stanford.edu/software/stk/faq.html), Sporth ([MIT](https://github.com/PaulBatchelor/Sporth/blob/master/LICENSE)), SoundPipe ([MIT](https://github.com/PaulBatchelor/Soundpipe/blob/master/LICENSE}) and EZAudio ([MIT](https://github.com/syedhali/EZAudio/blob/master/LICENSE))
