### ISSUE TITLE
AppStore Review Failed : Non public API : connected

### ISSUE THREAD

**Issue by moonsoo** [TheAmazingAudioEngine/TheAmazingAudioEngine#249]
i use TAAE1 but App Store review failed.

the reason was :

> Performance - 2.5.1
> Your app uses or references the following non-public APIs:
> connected
> The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

after i received the message, i found that name of method and TAAE uses the selector.

so i asked apple to :

> it just a one of method in 3rd party source's protocol.
> is it possible to reject an app that just has same method name in Apple's non-public API?

but Apple's response was :

> If this method is a coincidence, then it would be appropriate to contact the third party SDK provider to rename this selector.
> Once the selector has been renamed, please resubmit your app for review.

TAAE is using for one of my app's main feature.

if there is any idea to pass review or have any plan to modify the issue, please let me know

thanks.

**Comment by michaeltyson** [comment]
Oh dear. The issue arises from TAAE 1's built-in Audiobus support, and an over-zealous script on App Review's end.

If you comment out the code within "audiobusConnectionsChanged" from AEAudioController.m, and comment out "- (BOOL)connected;" from AEAudiobusForwardDeclarationsProtocol in AEAudiobusController+AudiobusStub.h, it should be resolved.

A more permanent fix will be forthcoming.
