### ISSUE TITLE
Multiple samples not playing at the same time in iOS 14

### ISSUE THREAD

**Issue by michaelcolville** [TheAmazingAudioEngine/TheAmazingAudioEngine#272]
We have an app built with TheAmazingAudioEngine, that since iOS 14 has had an issue where multiple samples wont play at the same time. I'm sure this isn't an issue with the framework and is probably something wrong in our app, but I was hoping someone has had a similar issue and knows how to resolve it?

There are no warnings or errors shown, and I have tried updating to the latest commit on master.

I appreciate this framework has been retired but we made the app a few years ago and would love to keep it working.

Thanks

**Comment by michaeltyson** [comment]
Hey @michaelcolville  - could you tell me a bit more about how you're using it, maybe with some (truncated) code samples? Hard to make suggestions without a bit more info.

**Comment by michaelcolville** [comment]
Thanks for getting back, I've had a look through the code, but I'm not the original author so I'm struggling to get a sample together. I'm trying to get in touch with previous developer to get more information for you.

**Comment by alexrothera** [comment]
Hey @michaelcolville I contacted @ajsantander but he doesn't have bandwidth to jump back in. And funny enough mentioned it was 5+ years ago, so your guess might be as good?

Mike, feel free to share any code you need here (obviously no analytics or PII)

**Comment by alexrothera** [comment]
@michaeltyson Hi Michael, nice to meet you!

**Context:**
A bit about our issue, our app Cove (http://www.cove-app.com/) is a mental health app recommended by the NHS as a free resource. Essentially Cove uses music-making to express yourself and capture feelings. Why I mention this:

1. Given Covid stresses, users downloading our app have gone through the roof.
2. This bug mentioned above has been flooding us with bug reports.

**Question**
Our developer that wrote the code integrating TheAmazingAudioEngine is no longer around, so we're majorly stuck at the moment. Any chance if we share code with you, you could help debug? Happy to chat over email if that's easier.

**Comment by michaeltyson** [comment]
Hi Alex - sounds like a bit of a pickle. If you’d like to send me an email we can discuss. I’m going to need to see the code.
