### ISSUE TITLE
Make checkResult function globally available

### ISSUE THREAD

**Issue by arielelkin** [TheAmazingAudioEngine/TheAmazingAudioEngine#30]
Many times we have to debug functions in our code that return an `OSStatus`, such as `AudioUnitSetParameter()`. Many classes of TAAE contain a very useful `checkResult` function which does that, for example, in `AEMixerBuffer.m`:

    checkResult(AudioUnitSetParameter(_mixerUnit, kMultiChannelMixerParam_Pan, kAudioUnitScope_Input, index, value, 0),
                "AudioUnitSetParameter(kMultiChannelMixerParam_Pan)");

It would be useful if `checkResult` would be available whenever one imports classes from TAAE!

**Comment by hoddez** [comment]
I believe this can be closed now:
https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/master/TheAmazingAudioEngine/AEUtilities.h#L300
