### ISSUE TITLE
How to allow simultaneous Play back and recording of audio using Amazing audio engine

### ISSUE THREAD

**Issue by puneetchd** [TheAmazingAudioEngine/TheAmazingAudioEngine#35]
The problem i am facing is that , one the user completes the recording of the audio and if he play it and at the same time he starts recording another audio , then the playing audio is also merged in the present recorded audio.
I dont want the output from speaker to be merged in the recording. It has been more than a week with this issue. All suggestions are welcome.

Puneet

**Comment by luisguerreirinho** [comment]
Hi there first of all awesome job Michael,

Now my question  is: is there something like the echo removal but for music?
thanks =)

**Comment by michaeltyson** [comment]
Cheers @luisguerreirinho =)

Not in Core Audio/TAAE{1,2}, I'm afraid; I'm not aware of anything in particular that'd do the job.

**Comment by luisguerreirinho** [comment]
So the best way is to turn down the volume of the playing track right?

On Thursday, 5 May 2016, Michael Tyson <notifications@github.com> wrote:

> Cheers @luisguerreirinho <https://github.com/luisguerreirinho> =)
>
> Not in Core Audio/TAAE{1,2}, I'm afraid; I'm not aware of anything in
> particular that'd do the job.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/issues/35#issuecomment-217047620>
>


-- 
Luís Guerreirinho

**Comment by michaeltyson** [comment]
Possibly - it really depends on the context
