### ISSUE TITLE
AERecorder currentTime not correct

### ISSUE THREAD

**Issue by zobkiw** [TheAmazingAudioEngine/TheAmazingAudioEngine#81]
AERecorder currentTime seems to lie a little. The number it returns is not what has been written to disk. It may be the time the object has been around - not sure. By counting the samples I found that currentTime would always be somewhere less than a second longer than the actual data written to the file. You can easily reproduce by running it, looking at the number after it closes but then open the file in any editor that shows the time/samples and see the difference.

**Comment by kurrak** [comment]
You can omit this by calling:
```
AEMixerBufferEnqueue([recorder valueForKey:@"mixer"], AEAudioSourceInput, NULL, 0, NULL);
```
before beginning recording. I'm using KVC here, since 'mixer' property is defined in .m file.

**Comment by jakobsa** [comment]
I also have an Issue with the currentTime property of AERecorder. The returned value is twice of what I expected.

**Comment by hakanw** [comment]
+1 on the last one. We have to divide the return value by 2 to get the right one :)

**Comment by jakobsa** [comment]
I am doing the same. I have a warning at this line of code for about a year now. I thought its time to ask the question.

**Comment by jakobsa** [comment]
I have a very wild guess. currentTime might be derived from a sample count. This sample count might be related the number of channels. And _audioDescription.mChannelsPerFrame is 2 in AEAudioFileWriter: beginWritingToFileAtPath:

**Comment by michaeltyson** [comment]
Whoops. My bad - the problem was (I think, anyway) that it's incrementing the time in the audio receiver callback. When you've got more that one source going into the recorder (like, the output + the input), it's incrementing twice for each time step.
